config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}

  root "home#index"

  resources :images, only: [:show, :create]

  resources :posts do
    resources :comments, only: [:create, :update], module: :posts
  end

  resources :comments do
    resources :comments, only: [:create, :update],  module: :comments
  end

  resources :users do
    scope module: :users do
      resources :pseudonyms, only: [:index, :new, :create]
    end
  end

  namespace :admin do
    get "", to: "dashboard#index"
    resources :users
    resources :posts
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :pseudonym

  has_many :comments, as: :commentable

  validates :user, :title, :body, presence: true
  validates_uniqueness_of :title, :scope => :pseudonym_id
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Post successfully created"
      redirect_to @post
    else
      flash[:alert] = "Oops something went wrong"
      redirect_to root_path
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = "Post permanently destroyed"
    redirect_to admin_posts_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < CommentsController
  before_action :set_commentable, only: :create
  before_action :set_comment, only: :update

  private

  def set_comment
    @comment = current_user.comments.find(params[:id])
  end

  def set_commentable
    @commentable = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :show
  before_action :authorize_action!, except: :show
  before_action :set_user_post, only: [:edit, :update]
  before_action :set_user_pseudonyms, only: [:new, :edit]

  def index
    @posts = current_user.posts
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new(post_params)

    if post.save
      flash[:notice] = "Post successfully created"
      redirect_to post
    else
      flash[:alert] = "Oops something went wrong"
      redirect_to root_path
    end
  end

  def edit;end

  def update
    if @post.update(post_params)
      flash[:notice] = "Post successfully created"
      redirect_to @post
    else
      flash[:alert] = "Oops something went wrong"
      redirect_to root_path
    end
  end

  private

  def authorize_action!
    authorize! params[:action].to_sym, Post
  end

  def set_user_post
    @post = current_user.posts.find(params[:id])
  end

  def set_user_pseudonyms
    @pseudonyms = current_user.pseudonyms
  end

  def post_params
    params.require(:post)
      .permit(:title, :body, :pseudonym_id)
      .merge(user_id: current_user.id)
  end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController
  before_action :set_post, only: :show

  def index
    @posts = current_user.posts
  end

  def show;end

  def new
    @post = Post.new(user: current_user)
  end

  def create
    post = Post.new(post_params)

    if post.save
      flash[:notice] = "Post successfully created"
      redirect_to root_path
    else
      flash[:alert] = "Oops something went wrong"
      redirect_to root_path
    end
  end

  private

  def set_post
    @post = current_user.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:user_id, :title, :body)
  end
end

app/views/admin/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.hidden_field :body, id: :post_body, class: "form-control" %>
    <trix-editor class="trix-content" input="post_body"></trix-editor>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= button_to "delete", admin_post_path(post), method: :delete, data: { confirm: "You sure?" } %>

app/views/admin/posts/edit.html.erb
<h1> Edit Post </h1>

<%= render 'form', post: @post %>

app/views/admin/posts/index.html.erb
<% @posts.each do |post| %>
  <p>
    <%= link_to post.title, admin_post_path(post.id) %> |
    <%= post.pseudonym.name %> |
    <%= link_to "Edit", edit_admin_post_path(post.id) %>
  </p>
<% end %>

app/views/admin/posts/show.html.erb
<div><%= @post.title %></div>

<p> By: <%= @post.pseudonym.name %> </p>

<p><%= link_to "Edit", edit_admin_post_path(@post.id) %></p>

<div class="trix-content"><%= sanitize @post.body %></div>

<%= render partial: "comments/form", locals: { commentable: @post } %>
<%= render partial: "comments/index", locals: { comments: @post.comments } %>