config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}

  root "home#index"

  resources :images, only: [:show, :create]

  resources :posts do
    resources :comments, only: [:create, :update], module: :posts
  end

  resources :comments do
    resources :comments, only: [:create, :update],  module: :comments
  end

  resources :users do
    scope module: :users do
      resources :pseudonyms, only: [:index, :new, :create]
    end
  end

  namespace :admin do
    get "", to: "dashboard#index"
    resources :users
    resources :posts
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :user_roles
  has_many :roles, through: :user_roles
  has_many :posts
  has_many :comments
  has_many :pseudonyms

  after_create :assign_default_role
  before_destroy :destroy_associations

  Role::TYPES.each do |user_role|
    define_method "#{user_role}?" do
      self.roles.include?(Role.send("#{user_role}"))
    end
  end

  def default_pseudonym
    pseudonyms.default.first || pseudonyms.first
  end

  private

  def assign_default_role
    UserRole.create(user: self, role: Role.user)
  end

  def destroy_associations
    pseudonyms.destroy_all
    user_roles.destroy_all
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_user, only: [:show, :edit]
  def index
    @users = User.all
  end

  def show
  end

  def edit
    @roles = Role.all
  end

  private

  def set_user
    @user = User.includes(:pseudonyms).find(params[:id])
  end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController
  before_action :set_post, only: :show

  def index
    @posts = current_user.posts
  end

  def show;end

  def new
    @post = Post.new(user: current_user)
  end

  def create
    post = Post.new(post_params)

    if post.save
      flash[:notice] = "Post successfully created"
      redirect_to root_path
    else
      flash[:alert] = "Oops something went wrong"
      redirect_to root_path
    end
  end

  private

  def set_post
    @post = current_user.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:user_id, :title, :body)
  end
end

app/controllers/users/pseudonyms_controller.rb
class Users::PseudonymsController < ApplicationController
  def index
    @pseudonyms = current_user.pseudonyms
  end

  def new
    @pseudonym = Pseudonym.new
  end

  def create
    pseudonym = Pseudonym.new(pseudonym_params)

    if pseudonym.save!
      flash[:notice] = "Pseudonym successfully created"
    else
      flash[:notice] = "Oops something went wrong"
    end

    redirect_to root_path
  end

  private

  def pseudonym_params
    params.require(:pseudonym).permit(:name, :user_id)
  end
end

app/views/admin/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :roles %>
    <%= form.select(:roles, @roles.collect {|r| [r.name, r.id] },
                    { prompt: "Please select" },
                    { multiple: true, selected: @user.roles.include?(r) }
                   ) %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<%# button_to "delete", admin_user_path(user), method: :delete, data: { confirm: "You sure?" } %>

app/views/admin/users/edit.html.erb
<%= render "form", user: @user %>

app/views/admin/users/index.html.erb
<% @users.each do |user| %>
  <p>
    <%= user.email %> |
    <%= link_to "Edit", edit_admin_user_path(user.id) %>
  </p>
<% end %>

app/views/admin/users/show.html.erb
Admin user show

<%= link_to "Edit #{user.email}", "/admin/users#{user.id}" %>